In [1]:
import pandas as pd 
import numpy as np

Nb for hw1

---
### Question 1: [Index] S&P 500 Stocks Added to the Index

**Which year had the highest number of additions (starting from 2020)?**

Using the list of S&P 500 companies from Wikipedia's [S&P 500 companies page](https://en.wikipedia.org/wiki/List_of_S%26P_500_companies), download the data including the year each company was added to the index.

Hint: you can use [pandas.read_html](https://pandas.pydata.org/docs/reference/api/pandas.read_html.html) to scrape the data into a DataFrame. You may need to add headers to make it work:
```python
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

# Fetch the HTML content with headers
response = requests.get(url, headers=headers)
```

Steps:
1. Create a DataFrame with company tickers, names, and the year they were added.
2. Extract the year from the addition date and calculate the number of stocks added each year.
3. Which (full) year had the highest number of additions, starting from 2020? 

▎ Note: When stocks are added to the S&P 500, they usually experience a price bump as investors and index funds buy     
  shares following the announcement.

▎ Context: 
> "Following the announcement, all four new entrants saw their stock prices rise in extended trading on Friday" - recent examples of S&P 500 additions include DASH, WSM, EXE, TKO in 2025 ([Nasdaq article](https://www.nasdaq.com/articles/sp-500-reshuffle-dash-tko-expe-wsm-join-worth-buying)).

*Additional*: How many current S&P 500 stocks have been in the index for more than 20 years?

In [ ]:

# Web Scraping for Macro
import requests
import io
from bs4 import BeautifulSoup
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
}
response = requests.get(url, headers=headers)
io_stream = io.StringIO(response.text)
# Read tables from HTML string
tables = pd.read_html(io_stream)


print(tables)

[    Symbol             Security             GICS Sector  \
0      MMM                   3M             Industrials
1      AOS          A. O. Smith             Industrials
2      ABT  Abbott Laboratories             Health Care
3     ABBV               AbbVie             Health Care
4      ACN            Accenture  Information Technology
..     ...                  ...                     ...
498    XYL           Xylem Inc.             Industrials
499    YUM          Yum! Brands  Consumer Discretionary
500   ZBRA   Zebra Technologies  Information Technology
501    ZBH        Zimmer Biomet             Health Care
502    ZTS               Zoetis             Health Care

                                GICS Sub-Industry    Headquarters Location  \
0                        Industrial Conglomerates    Saint Paul, Minnesota
1                               Building Products     Milwaukee, Wisconsin
2                           Health Care Equipment  North Chicago, Illinois
3                                   Biotechnology  North Chicago, Illinois
4                  IT Consulting & Other Services          Dublin, Ireland
..                                            ...                      ...
498  Industrial Machinery & Supplies & Components   White Plains, New York
499                                   Restaurants     Louisville, Kentucky
500            Electronic Equipment & Instruments   Lincolnshire, Illinois
501                         Health Care Equipment          Warsaw, Indiana
502                               Pharmaceuticals   Parsippany, New Jersey

     Date added      CIK      Founded
0    1957-03-04    66740         1902
1    2017-07-26    91142         1916
2    1957-03-04     1800         1888
3    2012-12-31  1551152  2013 (1888)
4    2011-07-06  1467373         1989
..          ...      ...          ...
498  2011-11-01  1524472         2011
499  1997-10-06  1041061         1997
500  2019-12-23   877212         1969
501  2001-08-07  1136869         1927
502  2013-06-21  1555280         1952

[503 rows x 8 columns],       vteS&P 500 companies                             vteS&P 500 companies.1
0                   Energy  APA Corporation Baker Hughes Chevron Corporati...
1                Materials  Air Products Albemarle Corporation Amcor Avery...
2              Industrials  3M A. O. Smith Allegion Ametek Automatic Data ...
3   Consumer discretionary  Airbnb Amazon Aptiv AutoZone Best Buy Booking ...
4         Consumer staples  Altria Archer Daniels Midland Brown-Forman Bun...
5              Health Care  Abbott Laboratories AbbVie Agilent Technologie...
6               Financials  Aflac Allstate American Express American Inter...
7   Information technology  Accenture Adobe Inc. Akamai Technologies AMD A...
8   Communication services  Alphabet Inc. AT&T Charter Communications Comc...
9              Real estate  Alexandria Real Estate Equities American Tower...
10               Utilities  AES Corporation Alliant Energy Ameren American...]

In [9]:
print(type(tables))
print(len(tables))
tables[0]

<class 'list'>
2

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [13]:
print(type(tables[0]))

<class 'pandas.DataFrame'>

In [11]:
tables[1]

      vteS&P 500 companies                             vteS&P 500 companies.1
0                   Energy  APA Corporation Baker Hughes Chevron Corporati...
1                Materials  Air Products Albemarle Corporation Amcor Avery...
2              Industrials  3M A. O. Smith Allegion Ametek Automatic Data ...
3   Consumer discretionary  Airbnb Amazon Aptiv AutoZone Best Buy Booking ...
4         Consumer staples  Altria Archer Daniels Midland Brown-Forman Bun...
5              Health Care  Abbott Laboratories AbbVie Agilent Technologie...
6               Financials  Aflac Allstate American Express American Inter...
7   Information technology  Accenture Adobe Inc. Akamai Technologies AMD A...
8   Communication services  Alphabet Inc. AT&T Charter Communications Comc...
9              Real estate  Alexandria Real Estate Equities American Tower...
10               Utilities  AES Corporation Alliant Energy Ameren American...

## STEPS

1. Create a DataFrame with company tickers, names, and the year they were added

In [17]:
df = tables[0][['Symbol','Security','Date added']]
df.head()

  Symbol             Security  Date added
0    MMM                   3M  1957-03-04
1    AOS          A. O. Smith  2017-07-26
2    ABT  Abbott Laboratories  1957-03-04
3   ABBV               AbbVie  2012-12-31
4    ACN            Accenture  2011-07-06

2. Extract the year from the addition date and calculate the number of stocks added each year.

In [22]:
df['Year'] = pd.to_datetime(df['Date added'], format='mixed').dt.year
df.head()

  Symbol             Security  Date added  Year
0    MMM                   3M  1957-03-04  1957
1    AOS          A. O. Smith  2017-07-26  2017
2    ABT  Abbott Laboratories  1957-03-04  1957
3   ABBV               AbbVie  2012-12-31  2012
4    ACN            Accenture  2011-07-06  2011

In [34]:
stocks_per_year = df.groupby(by='Year').size().reset_index().rename(columns={0:'stocks_per_year'})
stocks_per_year.head()

   Year  stocks_per_year
0  1957               52
1  1964                1
2  1965                2
3  1969                2
4  1970                2